name: ci-contracts

on:
  push:
    paths:
      - 'projects/algo-prophet-logic/**'
  pull_request:
    paths:
      - 'projects/algo-prophet-logic/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: projects/algo-prophet-logic
      - name: Compile contracts
        run: pnpm run build
        working-directory: projects/algo-prophet-logic
      - name: Run tests
        run: pnpm run test
        working-directory: projects/algo-prophet-logic
